### ISSUE TITLE
Remove my email from .travis.yml

### ISSUE THREAD

**Issue by revi** [WikiCanada/mw-config#2]
I'm not willing to receive any updates on this repo: Please delete my email from `.travis.yml`.

I don't want to add a list of my forks just to remove this, hence issue here.

Thank you.

![untitled](https://cloud.githubusercontent.com/assets/7630875/25802498/a4701504-342d-11e7-99ab-73874dbc3cbb.png)

**Comment by Amanda1234567** [comment]
Done. Although in the future you can just do a PR - I get notified for opened PR's but not for opened issues
